name: wordle_game
description: A new wordle game demo project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # CORE
  core: 
    path: ./modules/core

  # CONNECTIVITY
  http: ^0.13.4
  retrofit: ^2.2.0  

  # STATE MANAGEMENT
  provider: ^6.0.1
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1

  # UI
  flutter_spinkit: ^5.1.0
  loader_overlay: ^2.0.6
  cupertino_icons: ^1.0.2
  awesome_dialog: ^2.2.1

  # STORAGE
  shared_preferences: ^2.0.9
  #flutter_secure_storage: ^5.0.2


  # TOOLS
  equatable: ^2.0.3
  intl: ^0.17.0
  intl_utils: ^2.6.0
  json_annotation: ^4.4.0
  pedantic: ^1.11.1
  animations: ^2.0.2
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  retrofit_generator: ^2.1.0+1
  flutter_lints: ^1.0.0

dependency_overrides: 
  back_button_interceptor: ^5.0.2

flutter:

  uses-material-design: true


# flutter pub run intl_utils:generate 
flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: l10n
  output_dir: lib/generated